# Generated by Django 4.2.5 on 2024-08-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_matiere', models.CharField(max_length=100)),
                ('id_enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enseignant')),
            ],
        ),
    ]
