# Generated by Django 4.2.5 on 2024-08-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='matière',
        ),
    ]
