# Generated by Django 4.2.5 on 2024-08-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_enseignant_options_alter_enseignant_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_classe', models.CharField(max_length=255)),
                ('effectif_elelves', models.PositiveIntegerField()),
            ],
        ),
    ]
