# Generated by Django 4.2.5 on 2024-08-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_eleves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleves',
            old_name='classe',
            new_name='id_classe',
        ),
    ]
