# Generated by Django 5.1 on 2024-08-08 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_classe_effectif_elelves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='matricule',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eleves')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matiere')),
            ],
        ),
    ]
