# Generated by Django 5.1 on 2024-08-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_eleves_matricule_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
