# Generated by Django 5.1 on 2024-08-09 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eleves')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matiere')),
            ],
        ),
    ]
